services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    command: >
      postgres 
      -c listen_addresses='*'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - fead_network

  redis:
    image: redis:7-alpine
    networks:
      - fead_network

  backend:
    build:
      context: ./fead_product_backend
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 5 && 
             python manage.py migrate && 
             python manage.py collectstatic --noinput && 
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    depends_on:
      - postgres
      - redis
    networks:
      - fead_network

  celery_worker:
    build:
      context: ./fead_product_backend
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 10 && celery -A backend worker --loglevel=info"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - fead_network

  celery_beat:
    build:
      context: ./fead_product_backend
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 10 && celery -A backend beat --loglevel=info"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - fead_network

  frontend:
    build:
      context: ./fead_product_mini_app
      dockerfile: Dockerfile
    networks:
      - fead_network

  nginx:
    image: nginx:1.25
    ports:
      - "8040:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend
    networks:
      - fead_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  fead_network:
    driver: bridge